macro(recursive_add_executables dir numbers)
    file(GLOB subdirs ${dir}/*)
    foreach(subdir ${subdirs})
        if(IS_DIRECTORY ${subdir})
            get_filename_component(exec_name ${subdir} NAME_WE)
            set(has_subdir FALSE)
            file(GLOB potential_subdirs ${subdir}/*)

            foreach(pot_subdir ${potential_subdirs})
                if(IS_DIRECTORY ${pot_subdir})
                    set(has_subdir TRUE)
                    break()
                endif()
            endforeach()

            if(NOT has_subdir)
                file(GLOB srcs ${subdir}/*.cpp)
                add_executable(${numbers}_${exec_name} ${srcs})
            endif()
            if(has_subdir)
                string(REGEX MATCH "([0-9]+)_([A-Za-z0-9_]+)$" match_result ${subdir})
                if(match_result)
                    recursive_add_executables(${subdir} ${numbers}_${CMAKE_MATCH_1})
                endif()
            endif()
        endif()
    endforeach()
endmacro()
